-- print("^2Jim^7-^2Shops v^41^7.^47 ^7- ^2Shop Script by ^1Jimathy^7")

-- If you need support I now have a discord available, it helps me keep track of issues and give better support.

-- https://discord.gg/xKgQZ6wZvS

Config = {
	Debug = false, -- Enable to add debug boxes and message.
	img = "qb-inventory/html/images/", -- Set this to your inventory
	JimMenu = false, -- Enable this if you are using an updated qb-menu resource with icon support
	ApGov = false, -- Add support for AP-Goverment Tax 
	Peds = true, -- Set to true if you want Shops to have Peds
	Limit = false, -- Enable this to add Stash features, This adds limits to items and gets refilled at each restart
	MaxSlots = 15, -- Set this to your player inventory slot count, this is default "41"
	BlackMarket = false, -- enable to add blackmarket locations (defined at the bottom of this file)
	Measurement = "KG", -- Custom Weight measurement
	Gabz247 = false,  -- Enable if using gabz 247 stores
	GabzAmmu = false, -- Enable if using gabz Ammunation stores
	VendOverride = true, -- Enable this if you want all the vending machines to use this script
	RandomAmount = true, -- Sets wether a stash should have a "random" amount of stock or full.

	Scenarios = { -- List of scenarios the peds do, This is called "fun", much better than standing staring at the void.
		"WORLD_HUMAN_GUARD_PATROL",
		"WORLD_HUMAN_STAND_MOBILE",
		"WORLD_VEHICLE_BUSINESSMEN",
		"WORLD_FISH_IDLE",
		"WORLD_FISH_FLEE",
		"PROP_HUMAN_STAND_IMPATIENT",
		"WORLD_HUMAN_PARTYING",
		-- "WORLD_HUMAN_AA_SMOKE",
		-- "WORLD_HUMAN_DRUG_DEALER",
	},
	Products = {
		["normal"] = {
			{ name = "tosti", price = 2, amount = 50, },
			{ name = "water_bottle", price = 2, amount = 50, },
			{ name = "kurkakola", price = 2, amount = 50, },
			{ name = "twerks_candy", price = 2, amount = 50, },
			{ name = "snikkel_candy", price = 2, amount = 50, },
			{ name = "sandwich", price = 2, amount = 50, },
			{ name = "beer", price = 7, amount = 50, },
			{ name = "whiskey", price = 10, amount = 50, },
			{ name = "vodka", price = 70000, amount = 50, },
			{ name = "coke-diet", price = 5, amount = 40, },
			{ name = "cadbury-hotchocolate", price = 5, amount = 40, },
			{ name = "coke-peach", price = 5, amount = 40, },
			{ name = "apple", price = 5, amount = 40, },
			{ name = "fanta-peach", price = 5, amount = 40, },
			{ name = "marshy-marylands", price = 5, amount = 40, },
			{ name = "marshy-dorito.coolranch", price = 5, amount = 40, },
			{ name = "marshy-mccoys.fgs", price = 5, amount = 40, },
			{ name = "marshy-space-raiders", price = 5, amount = 40, },
			-- { name = "marshy-starmix", price = 5, amount = 40, },
			{ name = "jackolantern", price = 12, amount = 5},
			{ name = "scrunchie", price = 15, amount = 40, },
			{ name = "vape", price = 35, amount = 40, },
			{ name = "redwoodcigs", price = 15, amount = 20,},
			{ name = "cardiaquecigs", price = 25, amount = 40,},
			{ name = "yukoncigs", price = 5, amount = 90,},
			-- { name = "wallet", price = 100, amount = 10, info = {walletid = math.random(100,999)}, },
			-- { name = "bandage", price = 100, amount = 50, },
			{ name = "lighter", price = 2, amount = 50, },
			-- { name = "rolling_paper", price = 2, amount = 5000,  },
		},
		["burgershot"] = {
			{ name = "burgershot_bagsmall", price = 5, amount = 20,},
			{ name = "burgershot_bagbig", price = 10, amount = 30,},
			{ name = "burgershot_baggoat", price = 15, amount = 40,},
			{ name = "burgershot_bagcoffe", price = 23, amount = 50,},

		},
		["bar"] = {
			{ name = "water_bottle", price = 2, amount = 50, },
			{ name = "beer", price = 7, amount = 50, },
			{ name = "whiskey", price = 10, amount = 50, },
			{ name = "vodka", price = 70000, amount = 50, },
		},
		["hardware"] = {
			-- { name = "lockpick", price = 200, amount = 50, },
			{ name = "weapon_wrench", price = 250, amount = 250, },
			{ name = "weapon_hammer", price = 250, amount = 250, },
			-- { name = "weapon_bat", price = 500, amount = 50,  requiredGang = { "lostmc" } },  -- Gang only options in stores
			{ name = "repairkit", price = 250, amount = 50,  requiredJob = { ["mechanic"] = 0, ["police"] = 0 } },
			{ name = "screwdriverset", price = 350, amount = 50, },
			-- { name = "phone", price = 850, amount = 50, },
			-- { name = "radio", price = 250, amount = 50, },
			{ name = "binoculars", price = 50, amount = 50, },
			{ name = "firework1", price = 50, amount = 50, },
			{ name = "firework2", price = 50, amount = 50, },
			{ name = "firework3", price = 50, amount = 50, },
			{ name = "firework4", price = 50, amount = 50, },
			{ name = "fitbit", price = 400, amount = 150, },
			{ name = "cleaningkit", price = 150, amount = 150, },
			-- { name = "flask", price = 220, amount = 70,},
			{ name = "advancedrepairkit", price = 500, amount = 50,  requiredJob = { ["mechanic"] = 0 } },
			{ name = "repairkit", price = 15000, amout = 1000,},
		},
		["weedshop"] = {
			{ name = "joint", price = 10, amount = 1000, },
			{ name = "weapon_poolcue", price = 100, amount = 1000, },
			{ name = "weed_nutrition", price = 20, amount = 1000, },
			{ name = "empty_weed_bag", price = 2, amount = 1000, },
			{ name = "rolling_paper", price = 2, amount = 1000, },
		},
		["gearshop"] = {
			{ name = "diving_gear", price = 2500, amount = 10, },
			{ name = "jerry_can", price = 200, amount = 50, },
		},
		["leisureshop"] = {
			{ name = "parachute", price = 2500, amount = 10, },
			{ name = "binoculars", price = 50, amount = 50, },
			{ name = "diving_gear", price = 2500, amount = 10, },
		},
		["weapons"] = {
			{ name = "weapon_knife", price = 350, amount = 100, },
			{ name = "weapon_bat", price = 100, amount = 69, },
			{ name = "weapon_colbaton", price = 95, amount = 45, },
			{ name = "weapon_hatchet",price = 250, amount = 250, requiresLicense = true , requiredJob = { ["mechanic"] = 0, ["police"] = 0 } },
			{ name = "weapon_pistol", price = 2500, amount = 5, requiresLicense = true },
			{ name = "weapon_snspistol", price = 1500, amount = 5, requiresLicense = true },
			{ name = "weapon_vintagepistol", price = 4000, amount = 5, requiresLicense = true },
			{ name = "pistol_ammo", price = 250, amount = 250,  requiresLicense = true },
		},
		["coffeeplace"] = {
			{ name = "coffee", price = 5, amount = 500 },
			-- { name = "lighter", price = 2, amount = 50 },
		},
		["coffee"] = {
			-- {name = "coke-coffee" , price = 3 , amount = 2},
			{name = "coffee" , price = 3 , amount = 5},
		},
		["casino"] = {
			{ name = 'casinochips', price = 1, amount = 30 },
		},
		["electronics"] = {
			{ name = "phone", price = 150, amount = 50,},
			-- { name = "simcard", price = 260, amount = 70,},
			{ name = "radio", price = 3500, amount = 150,},
			-- { name = "radio", price = 250, amount = 50, },
			-- { name = "remotecontrol", price = 950, amount = 70,},
			-- { name = "screwdriverset", price = 350, amount = 50, },
			-- { name = "binoculars", price = 50, amount = 50, },
			{ name = "fitbit", price = 600, amount = 150,},
			-- { name = "fameboyadvanced", price = 950, amount = 15,},
			-- { name = "retrofameboy", price = 1500, amount = 10,},
			-- { name = "fameboy", price = 19000, amount = 110,},
		},
		["vending"] = {
			{ name = "kurkakola", price = 13, amount = 25, },
			{ name = "sprunk", price = 6, amount = 25, },
			{ name = "sprunklight", price = 5, amount = 25, },
			-- { name = "ecola", price = 100, amount = 25, },
			-- { name = "ecolalight", price = 100, amount = 25, },
			{ name = "twerks_candy", price = 4, amount = 25, },
			{ name = "snikkel_candy", price = 3, amount = 25, },
		},
		["weather"] = {
			{ name = "water_bottle", price = 3, amount = 50, },
		},
		["blackmarket"] = {
			{ name = "radioscanner", price = 6850, amount = 5 },
		},
		["pet"] = {
			{ name = "keepcompanionhusky", price = 1600, amount = 5 },
			{ name = "keepcompanionpoodle", price = 600, amount = 5 },
			{ name = "keepcompanionrottweiler", price = 960, amount = 5 },
			{ name = "keepcompanioncat", price = 4500, amount = 5 },
			{ name = "keepcompanionpug", price = 6700, amount = 5 },
			{ name = "keepcompanioncoyote", price = 1500, amount = 5 },
			{ name = "keepcompanionrabbit", price = 15500, amount = 5 },
			{ name = "keepcompanionhen", price = 770, amount = 5 },
			{ name = "keepcompanionmtlion2", price = 6600, amount = 5 },
		},
		["petfood"] = {
			{ name = "petfood", price = 1600, amount = 5 },
			{ name = "collarpet", price = 600, amount = 5 },
			{ name = "firstaidforpet", price = 960, amount = 5 },
			{ name = "petnametag", price = 4500, amount = 5 },
			{ name = "petwaterbottleportable", price = 6700, amount = 5 },
			{ name = "petgroomingkit", price = 1500, amount = 5 },
		},
		-- ["gas247"] = {
		-- 	{ name = "kurkakola", price = 10, amount = 25, },
		-- 	{ name = "sprunk", price = 14, amount = 25, },
		-- 	{name = "coffee" , price = 2.50 , amount = 12},
		-- 	{ name = "jerry_can", price = 450, amount = 50, },
		-- 	{ name = "coke-diet", price = 5, amount = 40, },
		-- 	{ name = "cadbury-hotchocolate", price = 5, amount = 40, },
		-- 	{ name = "coke-peach", price = 5, amount = 40, },
		-- 	{ name = "apple", price = 5, amount = 40, },
		-- 	{ name = "fanta-peach", price = 5, amount = 40, },
		-- 	{ name = "marshy-marylands", price = 5, amount = 40, },
		-- 	{ name = "marshy-dorito.coolranch", price = 5, amount = 40, },
		-- 	{ name = "marshy-mccoys.fgs", price = 5, amount = 40, },
		-- 	{ name = "marshy-space-raiders", price = 5, amount = 40, },
		-- 	{ name = "burgershot_bagbig", price = 10, amount = 30,},
		-- 	{ name = "burgershot_baggoat", price = 15, amount = 40,},
		-- 	{ name = "burgershot_matchaicecream", price = 7, amount = 12,},
		-- 	{ name = "burgershot_vanillaicecream", price = 4, amount = 16,},
		-- 	{ name = "burgershot_bigking", price = 19.95, amount = 5, },
		-- 	{ name = "cola", price = 2.35, amount = 100, },
		-- 	{ name = "hotchocolate", price = 4.45, amount = 70, },
		-- 	{ name = "tea", price = 4.54, amount = 25, },
		-- 	{ name = "water_bottle", price = 2, amount = 50, },
		-- 	{ name = "beer", price = 7, amount = 50, },
		-- 	{ name = "repairkit", price = 190, amount = 30, },
		-- 	{ name = "cleaningkit", price = 37, amount = 54, },
		-- },
	},
}

Config.SellCasinoChips = {
    coords = vector4(950.37, 34.72, 71.87, 33.82),
    ped = 'S_M_Y_CASINO_01',
    pricePer = 3,
}

Config.Locations = {
    -- 24/7 Locations
    ["247supermarket"] = {
        ["label"] = "24/7",
		["targetLabel"] = "Purchase goods",
		["type"] = "items",
		["model"] = {
			`ig_jimmyboston`,
			`u_m_m_filmdirector`,
			`csb_djblamadon`,
			`ig_agent`,
			`s_m_m_autoshop_01`,
			`s_f_y_hooker_03`,
			`csb_talcc`,
			`u_f_o_carol`,
			`cs_old_man1a`,
			`cs_janet`,
			`cs_andreas`,
			-- `s_m_m_ccrew_03`,
			-- `s_m_m_cop_01`,
			-- `csb_yusufamir`,
		},
		["killable"] = true,
		["logo"] = "https://i.imgur.com/bPcM0TM.png",
        ["coords"] = {
			vector4(-3242.12, 999.98, 12.83, 349.36),
			vector4(1728.28, 6416.03, 35.04, 242.45),
			vector4(1697.96, 4923.04, 42.06, 326.61),
			vector4(-1820.6, 794.73, 138.09, 141.99),
			vector4(1960.57, 3739.12, 32.34, 316.09),
			vector4(2556.19, 380.89, 108.62, 355.58),
			vector4(372.82, 327.3, 103.57, 255.46),
			vector4(161.21, 6642.32, 31.61, 223.57),
			vector4(-1112.27, -1361.7, 5.04, 215.58),
			vector4(24.48, -1345.21, 29.5, 271.05),
			vector4(-1221.38, -907.89, 12.33, 27.51),
			vector4(-706.13, -913.2, 19.22, 85.03),
			vector4(549.37, 2669.57, 42.16, 94.74),
			vector4(1165.06, -324.45, 69.21, 99.19),
			vector4(1134.11, -981.91, 46.42, 274.25),
		},
        ["products"] = Config.Products["normal"],
        ["blipsprite"] = 52,
		["blipcolour"] = 37,
    },
	["burgershot"] = {
        ["label"] = "BurgerShot",
		["type"] = "items",
		["model"] = {
			`ig_jimmyboston_02`,
			`csb_djblamadon`,
			`cs_old_man1a`,
			`s_m_m_autoshop_01`,
			`s_f_y_hooker_03`,
			`csb_talcc`,
			`cs_janet`,
			`cs_andreas`,
			`csb_mrs_r`,
			`csb_money`,
			`u_f_y_lauren`,
			`u_f_o_carol`,
		},
		["killable"] = true,
		["logo"] = "https://i.redd.it/burger-shot-modern-day-v0-qznk3ergmb3b1.png?width=3037&format=png&auto=webp&s=67236613beafd07c909e96905c2849f5b182c400",
        ["coords"] = {
			vector4(-1197.11, -890.89, 14.00, 300.98),
		},
        ["products"] = Config.Products["burgershot"],
        ["blipsprite"] = 106,
		["blipcolour"] = 59,
    },
    -- LTD Gasoline Locations
    -- ["ltdgasoline"] = {
    --     ["label"] = "LTD Gasoline",
	-- 	["type"] = "items",
	-- 	["model"] = {
	-- 		`s_m_m_autoshop_02`,
	-- 		`S_F_M_Autoshop_01`,
	-- 		`S_M_M_AutoShop_01`,
	-- 		`S_M_M_Autoshop_03`,
	-- 		`IG_Benny`,
	-- 		`IG_Benny_02`,
	-- 		`MP_F_BennyMech_01`,
	-- 	},
	-- 	["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/7/72/LTD-GTAO-LSTunersBanner.png",
    --     ["coords"] = {
	-- 		vector4(-47.42, -1758.67, 29.42, 47.26),
	-- 		vector4(-706.17, -914.64, 19.22, 88.77),
	-- 		vector4(-1819.53, 793.49, 138.09, 131.46),
	-- 		vector4(1164.82, -323.66, 69.21, 106.86),
	-- 	},
    --     ["products"] = Config.Products["normal"],
    --     ["blipsprite"] = 628,
	-- 	["blipcolour"] = 5,
    -- },
    -- Rob's Liquor Locations
    ["robsliquor"] = {
        ["label"] = "Rob's Liqour",
		["type"] = "items",
		["targetLabel"] = "Purchase liquor",
		["model"] = {
			`cs_nervousron`,
			`IG_RussianDrunk`,
			`U_M_Y_MilitaryBum`,
			`A_F_M_TrampBeac_01`,
			`A_M_M_Tramp_01`,
		},
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/d/de/RebsLiquor-GTAV.png",
        ["coords"] = {
			vector4(-1221.38, -907.89, 12.33, 27.51),
			vector4(-1486.82, -377.48, 40.16, 130.89),
			vector4(-2966.41, 391.62, 15.04, 87.82),
			-- vector4(1165.15, 2710.78, 38.16, 177.96),
		},
        ["products"] = Config.Products["bar"],
        -- ["blipsprite"] = 628,
		-- ["blipcolour"] = 31,
		["hideblip"] = true,
    },
    -- Hardware Store Locations
    ["hardware"] = {
        ["label"] = "Hardware Store",
		["type"] = "items",
		["model"] = {
			`s_m_m_autoshop_02`,
			`S_F_M_Autoshop_01`,
			`S_M_M_AutoShop_01`,
			`S_M_M_Autoshop_03`,
			`IG_Benny`,
			`IG_Benny_02`,
			`MP_F_BennyMech_01`,
		},
		["coords"] = {
			-- vector4(46.52, -1749.55, 29.64, 50.82),
			-- vector4(2747.76, 3472.9, 55.67, 243.88),
			-- vector4(-421.65, 6135.97, 31.88, 232.98),
		},
        ["products"] = Config.Products["hardware"],
        -- ["blipsprite"] = 402,
		-- ["blipcolour"] = 5,
		["hideblip"] = true,
    },
	-- Ammunation VANILLA Locations
    ["ammunation"] = {
        ["label"] = "Ammunation",
        ["targetLabel"] = "Purchase ammunation",
		["type"] = "weapons",
		["model"] = {
			`u_m_y_gunvend_01`,
			`u_m_y_antonb`,
			`u_m_y_caleb`,
			`ig_terry`,
			`ig_talcc`,
		},
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/a/aa/Ammunation-GTAV.png",
        ["coords"] = {
            vector4(808.94, -2158.99, 29.62, 330.26),
            vector4(-660.98, -933.6, 21.83, 154.74),
			vector4(1693.16, 3761.94, 34.71, 189.83),
            vector4(-330.72, 6085.81, 31.45, 190.52),
			vector4(253.41, -51.67, 69.94, 28.88),
			vector4(23.69, -1105.95, 29.8, 124.58),
            vector4(-1118.19, 2700.5, 18.55, 185.31),
            vector4(841.31, -1035.28, 28.19, 334.27),
			vector4(-1304.44, -395.68, 36.7, 41.85),
			vector4(2571.66, 297.04, 108.73, 95.54),
			vector4(76.42, -1578.67, 29.61, 47.74),
		},
        ["products"] = Config.Products["weapons"],
		-- ["hideblip"] = true,
		["blipsprite"] = 110,
		["blipcolour"] = 40,
    },
    -- Casino Locations
	-- ["casino"] = {
	-- 	["label"] = "Diamond Casino",
	-- 	["targetLabel"] = "Buy Chips",
	-- 	["type"] = "items",
	-- 	["model"] = {
	-- 		`U_F_M_CasinoShop_01`,
	-- 		`U_F_M_CasinoCash_01`,
	-- 		`S_F_Y_Casino_01`,
	-- 		`S_M_Y_Casino_01`,
	-- 	},
	-- 	["coords"] = {
	-- 		vector4(990.08, 30.35, 71.47, 94.81),
	-- 		vector4(990.96, 31.8, 71.47, 19.59),
	-- 	},
	-- 	["products"] = Config.Products["casino"],
	-- 	["hideblip"] = true,
	-- 	["blipsprite"] = 617,
	-- 	["blipcolour"] = 0,
	-- },
    -- ["casino2"] = {
	-- 	["label"] = "Casino Bar",
	-- 	["coords"] = { vector4(979.44, 25.4, 71.46, 0.75), },
	-- 	["type"] = "items",
	-- 	["model"] = {
	-- 		`S_M_M_HighSec_01`,
	-- 	},
	-- 	["products"] = Config.Products["bar"],
	-- 	["blipsprite"] = 52,
	-- 	["blipcolour"] = 0,
	-- },

    -- Weedshop Locations
    ["weedshop"] = {
		["label"] = "Smoke on the Water",
		["type"] = "items",
		["model"] = {
			`mp_f_weed_01`,
			`MP_M_Weed_01`,
			`A_M_Y_MethHead_01`,
			`A_F_Y_RurMeth_01`,
			`a_m_y_hippy_01`,
		},
		["coords"] = { 
			-- vector4(-1171.97, -1575.91, 4.39, 117.31), 
		},
		["products"] = Config.Products["weedshop"],
		-- ["blipsprite"] = 496,
		-- ["blipcolour"] = 2,
		["hideblip"] = true,
	},

    -- Bean Coffee Locations
    ["beancoffee"] = {
		["label"] = "Bean Machine Coffee",
		["type"] = "items",
		["targetLabel"] = "Purchase coffee",
		["model"] = {
			`A_F_Y_Hipster_02`,
		},
		["coords"] = {
			-- vector4(-628.97, 238.27, 81.9, 1.28),
		},
		["products"] = Config.Products["coffeeplace"],
		["hideblip"] = true,
    },

    -- Sea Word Locations
    ["seaworld"] = {
		["label"] = "Sea World",
		["type"] = "items",
		["targetLabel"] = "Purchase goods",
		["model"] = {
			`mp_m_boatstaff_01`,
			`a_m_y_beach_01`,
		},
		["coords"] = { vector4(-1686.48, -1072.53, 13.15, 49.85), },
		["products"] = Config.Products["gearshop"],
		["hideblip"] = true,
	},

    -- Leisure Shop Locations
    ["leisureshop"] = {
		["label"] = "Leisure Shop",
		["type"] = "items",
		["model"] = {
			`mp_m_boatstaff_01`,
			`a_m_y_beach_01`,
		},
		["coords"] = { vector4(-1505.67, 1512.29, 115.29, 244.94) },
		["products"] = Config.Products["leisureshop"],
		["hideblip"] = true,
		-- ["blipsprite"] = 52,
		-- ["blipcolour"] = 2,
    },
	["digitalden"] = {
		["label"] = "Digital Den",
		["targetLabel"] = "Purchase electronics",
		["type"] = "items",
		["model"] = {
			`S_M_M_LifeInvad_01`,
			`IG_Ramp_Hipster`,
			`A_M_Y_Hipster_02`,
			`A_F_Y_Hipster_01`,
			`IG_LifeInvad_01`,
			`IG_LifeInvad_02`,
			`CS_LifeInvad_01`,
		},
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/b/b5/DigitalDen-GTAV-Logo.png",
		["coords"] = {
			vector4(384.06, -827.34, 29.31, 273.91),
		},
		["products"] = Config.Products["electronics"],
		["blipsprite"] = 606,
		["blipcolour"] = 37,
	},
	["petshop"] = {
		["label"] = "PetShop",
		["targetLabel"] = "Purchase pet",
		["type"] = "items",
		["model"] = {
			`S_M_M_LifeInvad_01`,
			`IG_Ramp_Hipster`,
			`A_M_Y_Hipster_02`,
			`A_F_Y_Hipster_01`,
			`IG_LifeInvad_01`,
			`IG_LifeInvad_02`,
			`CS_LifeInvad_01`,
		},
		["logo"] = "https://media.istockphoto.com/id/892381986/vector/pet-shop-sign-with-cute-dog-and-cat.jpg?s=612x612&w=0&k=20&c=2De4xrNAqG4-wqvWF6_auPJoyPbwzPQHCb4j05c7e0M=",
		["coords"] = {
			vector4(559.83, 2747.49, 42.88, 269.83),
			},
		["products"] = Config.Products["pet"],
		["blipsprite"] = 463,
		["blipcolour"] = 4,
	},
	["petshopfood"] = {
		["label"] = "PedShop Food",
		["targetLabel"] = "Purchase ped goods",
		["type"] = "items",
		["model"] = {
			`S_M_M_LifeInvad_01`,
			`IG_Ramp_Hipster`,
			`A_M_Y_Hipster_02`,
			`A_F_Y_Hipster_01`,
			`IG_LifeInvad_01`,
			`IG_LifeInvad_02`,
			`CS_LifeInvad_01`,
		},
		["logo"] = "https://media.istockphoto.com/id/892381986/vector/pet-shop-sign-with-cute-dog-and-cat.jpg?s=612x612&w=0&k=20&c=2De4xrNAqG4-wqvWF6_auPJoyPbwzPQHCb4j05c7e0M=",
		["coords"] = {
			vector4(564.11, 2752.97, 42.88, 199.38),
			},
		["products"] = Config.Products["petfood"],
		["hideblip"] = true,
	},
	["lostmc"] = { -- More of a test/example - Gang accessible stores
		["label"] = "Lost MC",
		["type"] = "items",
		["gang"] = "lostmc",
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/b/b6/LostMCPatch-GTAV-Worn.png",
		["model"] = {
			`G_F_Y_Lost_01`,
			`G_M_Y_Lost_01`,
			`G_M_Y_Lost_02`,
			`G_M_Y_Lost_03`,
		},
		["coords"] = {
			vector4(999.59, -131.58, 74.06, 12.95),
		},
		["products"] = Config.Products["coffeeplace"], -- example using coffeplace info
		["hideblip"] = true,
	},

	["sandybar"] = { -- More of a test/example - Gang accessible stores
		["label"] = "Grand Seniora Bar",
		["type"] = "items",
		["targetLabel"] = "Purchase bar goods",
		["logo"] = "https://iconape.com/wp-content/png_logo_vector/bar-logo.png",
		["model"] = {
			`s_m_y_barman_01`,
			`cs_barry`,
			`mp_f_chbar_01`,
			`s_f_y_bartender_01`,
		},
		["coords"] = {
			vector4(1984.42, 3054.66, 47.22, 247.34),
		},
		["products"] = Config.Products["bar"], -- example using coffeplace info
		["blipsprite"] = 93,
		["blipcolour"] = 0,
},

}

--if Gabz locations are enabled, override their coords with these
if Config.Gabz247 then
	Config.Locations["247supermarket"]["coords"] = {
		vector4(24.91, -1346.86, 29.5, 268.37),
		vector4(-3039.64, 584.78, 7.91, 21.88),
		vector4(-3242.73, 1000.46, 12.83, 2.08),
		vector4(1728.44, 6415.4, 35.04, 243.26),
		vector4(1697.96, 4923.04, 42.06, 326.61),
		vector4(1960.26, 3740.6, 32.34, 300.45),
		vector4(548.67, 2670.94, 42.16, 101.0),
		vector4(2677.97, 3279.95, 55.24, 325.89),
		vector4(2556.8, 381.27, 108.62, 359.15),
		vector4(373.08, 326.75, 103.57, 253.14),
		vector4(161.2, 6641.74, 31.7, 221.02),
		vector4(812.86, -782.01, 26.17, 270.01),
	}
end
if Config.GabzAmmu then
	Config.Locations["ammunation"]["coords"] = {
		vector4(-659.16, -939.79, 21.83, 91.25),
		vector4(812.85, -2155.16, 29.62, 355.85),
		vector4(1698.04, 3757.43, 34.71, 136.69),
		vector4(-326.03, 6081.17, 31.45, 138.33),
		vector4(246.87, -51.3, 69.94, 335.47),
		vector4(18.71, -1108.24, 29.8, 158.71),
		vector4(2564.85, 298.83, 108.74, 283.17),
		vector4(-1112.4, 2697.08, 18.55, 152.96),
		vector4(841.16, -1028.63, 28.19, 294.2),
		vector4(-1310.71, -394.33, 36.7, 340.51),
	}
end
if Config.BlackMarket then
	Config.Locations["blackmarket"] = {
		["label"] = "Black Market",
		["type"] = "items",
		["model"] = {
			`mp_f_weed_01`,
			`MP_M_Weed_01`,
			`A_M_Y_MethHead_01`,
			`A_F_Y_RurMeth_01`,
			`A_M_M_RurMeth_01`,
			`MP_F_Meth_01`,
			`MP_M_Meth_01`,
		},
		["coords"] = {
			vector4(776.24, 4184.08, 41.8, 92.12),
			vector4(2482.51, 3722.28, 43.92, 39.98),
			vector4(462.67, -1789.16, 28.59, 317.53),
			vector4(-115.15, 6369.07, 31.52, 232.08),
			vector4(752.52, -3198.33, 6.07, 301.72)
		},
		["products"] = Config.Products["blackmarket"],
		["hideblip"] = true,
	}
end

if Config.VendOverride then
	Config.Locations["vendingmachine"] = {
		["label"] = "Vending Machine",
		["targetIcon"] = "fas fa-calculator",
		["targetLabel"] = "Vending Machine",
		["type"] = "items",
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/d/d4/Ecola-GTAO-LSTunersBanner.png",
		["model"] = { -- You can add more models to this, but these make the most sense for the vending machine stuff
			`prop_vend_soda_02`,
			`prop_vend_fridge01`, 
			`prop_vend_soda_01`,
			`prop_vend_soda_02`,
			`prop_vend_snak_01`,
			`prop_vend_snak_01_tu`,
			`ch_chint10_vending_smallroom_01`,
			`sf_prop_sf_vend_drink_01a`,
		},
		["coords"] = { -- If you want to place custom vending machine locations
			-- vector4(131.13, -3007.16, 7.04, 0.0), -- GABZ LS Tuners
		},
		["products"] = Config.Products["vending"],
	}
	Config.Locations["vendingmachine2"] = {
		["label"] = "Weather Machine",
		["targetIcon"] = "fa-solid fa-cash-register",
		["targetLabel"] = "Weather Machine",
		["type"] = "items",
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/d/d4/Ecola-GTAO-LSTunersBanner.png",
		["model"] = { -- You can add more models to this, but these make the most sense for the vending machine stuff
			`prop_watercooler_dark`,
			`prop_vend_water_01`,
			`prop_watercooler`,
		},
		["coords"] = { -- If you want to place custom vending machine locations
			-- vector3(383.83, -1412.17, 36.91), -- GABZ LS Tuners
		},
		["products"] = Config.Products["weather"],
	}
	Config.Locations["vendingmachine3"] = {
		["label"] = "Coffee Machine",
		["targetIcon"] = "fa-solid fa-cash-register",
		["targetLabel"] = "Coffee Machine",
		["type"] = "items",
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/d/d4/Ecola-GTAO-LSTunersBanner.png",
		["model"] = { -- You can add more models to this, but these make the most sense for the vending machine stuff
			`prop_coffee_mac_02`,
			`prop_coffee_mac_01`,
			`prop_vend_coffe_01`,
		},
		["coords"] = { -- If you want to place custom vending machine locations
			-- vector3(383.83, -1412.17, 36.91), -- GABZ LS Tuners
		},
		["products"] = Config.Products["coffee"],
	}
end
Config.ItemModels = {
	["repairkit"] = `v_ind_cs_toolbox4`,
	["advancedrepairkit"] = `v_ind_cs_toolbox4`,
	["phone"] = `p_amb_phone_01`,
	["tosti"] = `prop_sandwich_01`,
	["sandwich"] = `prop_sandwich_01`,
	["water_bottle"] = `ba_prop_club_water_bottle`,
	["kurkacola"] = `prop_ecola_can`,
	["sprunk"] = `v_res_tt_can03`,
	["sprunklight"] = `v_res_tt_can03`,
	["ecola"] = `prop_ecola_can`,
	["ecolalight"] = `prop_ecola_can`,
	["twerks_candy"] = `prop_choc_pq`,
	["snikkel_candy"] = `prop_choc_pq`,
	["beer"] = `prop_sh_beer_pissh_01`,
	["whiskey"] = `prop_whiskey_bottle`,
	["vodka"] = `prop_vodka_bottle`,
	["lighter"] = `lux_prop_lighter_luxe`,

	["screwdriverset"] = `prop_tool_screwdvr01`,
	["radio"] = `prop_cs_hand_radio`,
	["binoculars"] = `v_serv_ct_binoculars`,
	["cleaningkit"] = `prop_huf_rag_01`,

	["casinochips"] = `vw_prop_chip_100dollar_st`,
	["diving_gear"] = `p_s_scuba_tank_s`,
	["jerry_can"] = `prop_jerrycan_01a`,
	["parachute"] = `p_parachute_s_shop`,

	["coffee"] = `prop_fib_coffee`,
	["fitbit"] = `p_watch_02`,
	["radioscanner"] = `prop_police_radio_main`,
	--Weapons
	["weapon_bat"] = `p_cs_bbbat_01`,
	["weapon_knife"] = `prop_w_me_knife_01`,
	["weapon_hammer"] = `w_me_hammer`,
	["weapon_hatchet"] = `prop_w_me_hatchet`,
	['weapon_dagger'] = `prop_w_me_dagger`,
	['weapon_bottle'] = `prop_w_me_bottle`,
	['weapon_crowbar'] = `prop_ing_crowbar`,
	['weapon_flashlight'] = `w_me_flashlight`,
	['weapon_golfclub'] = `prop_golf_iron_01`,
	['weapon_knuckle'] = `w_me_knuckle`,
	['weapon_machete'] = `prop_ld_w_me_machette`,
	['weapon_switchblade'] = `w_me_switchblade`,
	['weapon_nightstick'] = `w_me_nightstick`,
	['weapon_wrench'] = `v_ind_cs_wrench`,
	['weapon_battleaxe'] = `w_me_battleaxe`,
	['weapon_poolcue'] = `w_me_poolcue`,
	['weapon_handcuffs']  = `prop_cs_cuffs_01`,
	['weapon_bread']  = `v_res_fa_bread01`,
	['weapon_stone_hatchet'] = `w_me_stonehatchet`,

	['weapon_pistol'] = `w_pi_pistol`,
	['weapon_pistol_mk2'] = `w_pi_pistolmk2`,
	['weapon_combatpistol'] = `w_pi_combatpistol`,
	['weapon_appistol']  = `w_pi_appistol`,
	['weapon_stungun'] 	 = `w_pi_stungun`,
	['weapon_pistol50']  = `w_pi_pistol50`,
	['weapon_snspistol']  = `w_pi_sns_pistol`,
	['weapon_heavypistol']  = `w_pi_heavypistol`,
	['weapon_vintagepistol'] = `w_pi_vintage_pistol`,
	['weapon_flaregun'] = `w_pi_flaregun`,
	--['weapon_marksmanpistol'] = ``,
	['weapon_revolver'] = `w_pi_revolver`,
	['weapon_revolver_mk2'] = `w_pi_revolvermk2`,
	['weapon_doubleaction'] = `w_pi_wep1_gun`,
	['weapon_snspistol_mk2'] = `w_pi_sns_pistolmk2`,
	['weapon_raypistol'] = `w_pi_raygun_ev`,
	['weapon_ceramicpistol'] = `w_pi_ceramic_pistol`,
	['weapon_navyrevolver'] = `w_pi_wep2_gun`,
	--['weapon_gadgetpistol'] = ``,
	['weapon_microsmg'] = `w_sb_microsmg`,
	['weapon_smg'] = `w_sb_smg`,
	['weapon_smg_mk2'] = `w_sb_smgmk2`,
	['weapon_assaultsmg'] = `w_sb_assaultsmg`,
	['weapon_combatpdw'] = `w_sb_pdw`,
	--['weapon_machinepistol'] = ``,
	['weapon_minismg'] = `w_sb_minismg`,
	['weapon_raycarbine'] = `w_ar_srifle`,
	['weapon_pumpshotgun'] = `w_sg_pumpshotgun`,
	['weapon_pumpshotgun_mk2'] = `w_sg_pumpshotgunmk2`,
	['weapon_sawnoffshotgun'] = `w_sg_sawnoff`,
	['weapon_assaultshotgun'] = `w_sg_assaultshotgun`,
	['weapon_bullpupshotgun'] = `w_sg_bullpupshotgun`,
	['weapon_musket'] = `w_ar_musket`,
	['weapon_heavyshotgun'] = `w_sg_heavyshotgun`,
	['weapon_dbshotgun'] = `w_sg_doublebarrel`,
	--['weapon_autoshotgun'] = ``,
	--['weapon_combatshotgun'] = ``,

	['weapon_assaultrifle'] = `w_ar_assaultrifle`,
	['weapon_assaultrifle_mk2'] = `w_ar_assaultriflemk2`,
	['weapon_carbinerifle'] = `w_ar_carbinerifle`,
	['weapon_carbinerifle_mk2'] = `w_ar_carbineriflemk2`,
	['weapon_advancedrifle'] = `w_ar_advancedrifle`,
	['weapon_specialcarbine'] = `w_ar_specialcarbine`,
	['weapon_specialcarbine_mk2'] = `w_ar_specialcarbinemk2`,
	['weapon_bullpuprifle'] = `w_ar_bullpuprifle`,
	['weapon_bullpuprifle_mk2'] = `w_ar_bullpupriflemk2`,
	['weapon_compactrifle']  = `w_ar_assaultrifle_smg`,
	['weapon_militaryrifle'] = `w_ar_heavyrifleh`,
	['weapon_mg'] = `w_mg_mg`,
	['weapon_combatmg'] = `w_mg_combatmg`,
	['weapon_combatmg_mk2'] = `w_mg_combatmgmk2`,
	['weapon_gusenberg'] = `w_sb_gusenberg`,

	['weapon_sniperrifle'] = `w_sr_sniperrifle`,
	['weapon_heavysniper'] = `w_sr_heavysniper`,
	['weapon_heavysniper_mk2'] = `w_sr_heavysnipermk2`,
	['weapon_marksmanrifle'] = `w_sr_marksmanrifle`,
	['weapon_marksmanrifle_mk2'] = `w_sr_marksmanriflemk2`,
	--['weapon_remotesniper'] = ``,
	['weapon_rpg'] = `w_lr_rpg`,
	['weapon_grenadelauncher'] = `w_lr_grenadelauncher`,
	['weapon_grenadelauncher_smoke'] = `w_lr_grenadelauncher`,
	['weapon_minigun'] = `prop_minigun_01`,
	['weapon_firework'] = `w_lr_firework`,
	['weapon_railgun'] = `w_ar_railgun`,
	--['weapon_hominglauncher'] = ``,
	--['weapon_compactlauncher'] = ``,
	--['weapon_rayminigun'] = ``,
	['weapon_grenade'] = `w_ex_grenadefrag`,
	['weapon_bzgas'] = `prop_gas_grenade`,
	['weapon_molotov'] = `w_ex_molotov`,
	--['weapon_stickybomb'] = ``,
	['weapon_proxmine'] = `gr_prop_gr_pmine_01a`,
	['weapon_snowball'] = `w_ex_snowball`,
	['weapon_pipebomb'] = `w_ex_pipebomb`,
	['weapon_ball'] = `w_am_baseball`,
	['weapon_smokegrenade'] = `w_ex_grenadesmoke`,
}
