--[[ ===================================================== ]]--
--[[         MH Vehicle Key Item Script by MaDHouSe        ]]--
--[[ ===================================================== ]]--

Config = {}
Config.KeyItem         = "vehiclekey" -- Default "vehiclekey", you can change this to your own vehiclekey items
Config.IgnoreAdmins    = false        -- Default true, admins will be ignore by the system and has always access to drive
Config.NoLockVehicles = {}


-- add job like the cardealer to have access (set Config.MustOwnVehicles to true if you use this.)
Config.IgnoreForKeyItem = {
    ['cardealer'] = true,
}

-- this is used to give the npc keys a owner name. (don't remove it, but you can add more names if you want.)
Config.NPCNames = {
    'Adrianus',
    'Ahmed',
    'Aidan',
    'Aimée',
    'Aisha',
    'Alaina',
    'Albert',
    'Bauke',
    'Beau',
    'Ben',
    'Benjamin',
    'Bente',
    'Benthe',
    'Cailey',
    'Caillen',
    'Caitlynn',
    'Daan',
    'Dae',
    'Dain',
    'Daisy',
    'Eben',
    'Edith',
    'Eefje',
    'Egbert',
    'Egidia',
    'Faas',
    'Faber',
    'Fabian',
    'Fajah',
    'Falke',
    'Geert-Jan',
    'Gemma',
    'Geralda',
    'Gerco',
    'Gerdine',
    'Hailey',
    'Hananja',
    'Hanna',
    'Hannah',
    'Hannes',
    'Hein',
    'Helena',
    'Henk',
    'Henrick',
    'Ibrahim',
    'Ilay',
    'Ilse',
    'Ilvy',
    'Jacco',
    'Jace',
    'Jack',
    'Jackie',
    'Jacoba',
    'Jacques',
    'Kaat',
    'Kai',
    'Kailey',
    'Kaily',
    'Kaira',
    'Klaas',
    'Lana',
    'Lanah',
    'Lara',
    'Laresse',
    'Maaike',
    'Maarten',
    'Maddox',
    'Madee',
    'Madelief',
    'Nadine',
    'Naher',
    'Nanouk',
    'Naomi',
    'Nasser',
    'Ole',
    'Olivia',
    'Olivier',
    'Oscar',
    'Otis',
    'Otte',
    'Oumayra',
    'Owen',
    'Pauline',
    'Pedro',
    'Pepijn',
    'Peter',
    'Philou',
    'Phoebe',
    'Pierre',
    'Piet',
    'Pieter',
    'Pijke',
    'Pim',
    'Pip',
    'Pleun',
    'Quenthe',
    'Quinten',
    'Quinty',
    'Rachele',
    'Raeven',
    'Raf',
    'Rafael',
    'Raff',
    'Ralf',
    'Ralph',
    'Ranomi',
    'Cristian',
    'Andrei',
    'Ravi',
    'Ray',
    'Rebecca',
    'Sabel',
    'Safa',
    'Salah',
    'Salome',
    'Salvano',
    'Sam',
    'Samiir',
    'Samuel',
    'Tabitha',
    'Talitha',
    'Tamara',
    'Tara',
    'Tasnim',
    'Tatum',
    'Vajen',
    'Valerie',
    'Vanessa',
    'Vera',
    'Vicky',
    'Vienna',
    'Vienne',
    'Vieve',
    'Wess',
    'Wessel',
    'Wies',
    'Wietse',
    'Wilbert',
    'Xemm',
    'Yanieck',
    'Yara',
    'Yasser',
    'Yde',
    'Yeliz',
    'Yenthe',
    'Zahra',
    'Zara',
    'Ziva',
    'Zoë',
    'Zoey',
}